version: '3.3'
services:
    web:
        env_file:
            - .env
        build: .
        ports:
            - '3000:3000'
        networks:
            - ecomm-app
        depends_on:
            - mongo
    mongo:
        image: mongo
        volumes:
            - mongodb:/data/db
        ports:
            - '27017:27017'
        networks:
            - ecomm-app

volumes:
    mongodb:

networks:
    ecomm-app:
        driver: bridge
