apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mongo
spec:
    serviceName: database
    replicas: 1
    selector:
        matchLabels:
            app: database
    template:
        metadata:
            labels:
                app: database
                selector: mongo
        spec:
            containers:
                - name: mongo
                  image: mongo:latest
---

